# Generated by Django 3.1.7 on 2021-03-23 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('date_removed', models.DateTimeField(blank=True, null=True, verbose_name='Date Removed')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True, verbose_name='Date Uploaded')),
                ('csv_file', models.FileField(blank=True, upload_to='teachers/bulkupload', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='File Upload')),
                ('image_zip_file', models.FileField(blank=True, upload_to='teachers/bulkupload/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='zip File Image Upload')),
            ],
            options={
                'ordering': ['date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('date_removed', models.DateTimeField(blank=True, null=True, verbose_name='Date Removed')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Phone Number')),
                ('room', models.CharField(blank=True, max_length=255, verbose_name='Room Number')),
                ('profile_pic', models.ImageField(blank=True, default='default-placeholder-image.png', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'jpg', 'png'])], verbose_name='Profile picture')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Valid')),
                ('subjects', models.ManyToManyField(blank=True, to='core.Subject', verbose_name='Subjects Taught')),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'email'],
            },
        ),
    ]
